$(function(){$('.navbar-toggle').click(function(){$(this).toggleClass('act');if($(this).hasClass('act')){$('.main-menu').addClass('act')}else{$('.main-menu').removeClass('act')}});$(document).on('click','.page-scroll a',function(event){var $anchor=$(this);$('html, body').stop().animate({scrollTop:$($anchor.attr('href')).offset().top},1000,'easeInOutExpo');event.preventDefault()});$('body').scrollspy({target:'.site-header',offset:10});var $section=$('.section-skills');function loadDaBars(){$('.progress .progress-bar').progressbar({transition_delay:500})}
$(document).bind('scroll',function(ev){var scrollOffset=$(document).scrollTop();var containerOffset=$section.offset().top-window.innerHeight;if(scrollOffset>containerOffset){loadDaBars();$(document).unbind('scroll')}});if($(".section-counters .start").length>0){$(".section-counters .start").each(function(){var stat_item=$(this),offset=stat_item.offset().top;$(window).scroll(function(){if($(window).scrollTop()>(offset-1000)&&!(stat_item.hasClass('counting'))){stat_item.addClass('counting');stat_item.countTo()}})})};$('#infinity').data('countToOptions',{onComplete:function(value){count.call(this,{from:value,to:value+1})}});$('#infinity').each(count);function count(options){var $this=$(this);options=$.extend({},options||{},$this.data('countToOptions')||{});$this.countTo(options)}
var s=skrollr.init({forceHeight:!1,smoothScrolling:!1,mobileDeceleration:0.004,mobileCheck:function(){return!1}})});function initSlideshows(){const slideshowContainers=document.querySelectorAll('.slideshow-container');slideshowContainers.forEach((slideshowContainer)=>{let slideIndex=0;const slides=slideshowContainer.getElementsByClassName('slides');slides[slideIndex].classList.add('active');function showSlides(){for(let i=0;i<slides.length;i++){slides[i].classList.remove('active')}
slideIndex++;if(slideIndex>=slides.length){slideIndex=0}
slides[slideIndex].classList.add('active');setTimeout(showSlides,3000)}
showSlides()})}
initSlideshows();function sendEmail(){var name=document.getElementById("name").value;var subject=document.getElementById("subject").value;var phone=document.getElementById("phone").value;var message=document.getElementById("message").value;var body=`Name: ${name}%0AEmail: ${email}%0APhone: ${phone}%0A%0A${message}`;window.location.href=`mailto:kellydianga711@gmail.com?subject=${encodeURIComponent(subject)}&body=${body}`}
const canvas=document.getElementById('pdf-canvas');const context=canvas.getContext('2d');function loadPDF(){const pdfUrl='pdfs/Blue Simple Professional CV Resume (4).pdf';pdfjsLib.getDocument(pdfUrl).promise.then(pdf=>{pdf.getPage(1).then(page=>{const viewport=page.getViewport({scale:1.5});canvas.height=viewport.height;canvas.width=viewport.width;const renderContext={canvasContext:context,viewport:viewport};page.render(renderContext)})})}
document.getElementById('pdfBtn').addEventListener('click',()=>{document.getElementById('pdfModal').style.display='block';loadPDF()});document.getElementById('closeBtn').addEventListener('click',()=>{document.getElementById('pdfModal').style.display='none'})
